Traceback (most recent call last):
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def ll(th_china, th_mexico, data):
    return sum([log(prob(th_china, th_mexico, w)) for w in data])

data = [c,c,m,c] # how does this graph look with all Cs?
smle.plot_mle_graph(lambda x,y: ll(x,y, data), mle(data), 
                    x_label='China',y_label='Mexico')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      2[0m     [38;5;28;01mreturn[39;00m [38;5;28msum[39m([log(prob(th_china, th_mexico, w)) [38;5;28;01mfor[39;00m w [38;5;129;01min[39;00m data])
[1;32m      4[0m data [38;5;241m=[39m [c,c,m,c] [38;5;66;03m# how does this graph look with all Cs?[39;00m
[0;32m----> 5[0m [43msmle[49m[38;5;241m.[39mplot_mle_graph([38;5;28;01mlambda[39;00m x,y: ll(x,y, data), mle(data), 
[1;32m      6[0m                     x_label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mChina[39m[38;5;124m'[39m,y_label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mMexico[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'smle' is not defined
NameError: name 'smle' is not defined

